### ISSUE TITLE
When climbing stairs in Lumbridge castle the plugin stops functioning

### ISSUE THREAD

**Issue by M1ch431** [Trevor159/runelite-chatbox-opacity#1]
Probably happens in other situations too when the chatbox background is changed

**Comment by Trevor159** [comment]
Can you take a gif or video of this happening? Also, what version of the client are you on?

**Comment by Trevor159** [comment]
I can't replicate this.

**Comment by M1ch431** [comment]
Now it's not happening. I uninstalled then reinstalled the plugin. The issue initially happened during first install and setting the chatbox to be fully transparent. Just installed OBS and was ready to record too lol.

**Comment by Trevor159** [comment]
I changed the plugin slightly so maybe you had the old version or something, glad it's fixed.

**Comment by M1ch431** [comment]
I'll try this out on a fresh installation and see if I can reproduce it. I experienced the issue on the latest version

**Comment by M1ch431** [comment]
Not really sure what caused this. I'd just chalk this up as a one-off thing. Just cleared all my settings and reinstalled Runelite and it didn't happen.
